name: main
on:
  push:
    branches:
    - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Kaniko build
      uses: aevea/action-kaniko@master
      with:
        image: jordanyong/express-01
        tag: ${{ github.sha }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        cache: true
        cache_registry: aevea/cache
